# Header
menu: # 菜单
  主页: /
  技术: tags/tech
  随笔: tags/something
  相册: /photos

subtitle: # 博客名字下面的个性签名

# SubNav
subnav: # 页面左侧的社交图标
  github: "https://github.com/你的Github"
  #weibo: "微博主页链接"
  zhihu: "知乎主页链接"
  #qq: "#"
  weixin: "微信二维码链接"
  #douban: "豆瓣主页链接"
  #mail: "邮箱"
# RSS 功能
rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content
excerpt_link: more # md文章中插入 <!-- more --> 就会截断文章显示摘要，在对应位置显示"more"
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: true
# fancybox
fancybox: true

# 打赏功能设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
reward_wording: '谢谢大佬' # 打赏显示的字
# 支付宝收款二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /assets/img/alipay.png
# 微信收款二维码图片地址
weixin: /assets/img/wxpay.png

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: '475fe3bc980b2bb65bae8bbf8de77994' # 百度分析
google_analytics: ''
favicon: /assets/img/myico.ico # 网页加载图标

#你的头像
avatar: /assets/img/heichuan.png 

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  #header: '#4d4d4d'
  header: '#00000'
  # 右滑板块背景
  #slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'
  slider: 'linear-gradient(200deg,#1E90FF,#B0C4DE)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 配置gitalk
gitalk:
  enable: true
  owner: Username
  repo: '存储评论的 repo'
  clientID: ''
  clientSecret: ''
  admin: Username
  distractionFreeMode: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
friends: true # 友链
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends: # 友链
  水恒涛的博客: http://hengtao.top/
  刘看山的博客: https://xiangyuliuseu.github.io/
  吕归尘的博客: https://guichenlv.github.io/

# aboutme: 你好<br><br>这是我的博客<br>很高兴认识大家<br><br>Le vent se lève,<br>il faut tenter de vivre
